# Generated by Django 4.2.6 on 2023-11-11 14:46

from django.db import migrations, models
from spacare.quyen.models import Quyen


def migration_data_quyen(apps, schema_editor):
    list_quyen = []
    quyen_data = ["chu_spa", "nhan_vien_spa", "le_tan", "ke_toan", "khach_hang"]
    for quyen in quyen_data:
        list_quyen.append(Quyen(ten_quyen=quyen))
    Quyen.objects.bulk_create(list_quyen)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_quyen", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(migration_data_quyen),
    ]
